### ISSUE TITLE
error when running demo - add_analogies

### ISSUE THREAD

**Issue by SolveigHelene** [zouharvi/pwesuite#10]
I have come across a error messages when evaluating on sound analogies in the demo script in add_analogies.py.

The error message is:
/pwesuite/create_dataset/add_analogies.py", line 154, in find_single_perturbation_pairs
        feature_vectors[tuple(ft.fts(x).numeric())].append(x)
                              ^^^^^^^^^^^^^^^^^
    AttributeError: 'dict' object has no attribute 'numeric'
    
The problem seems to occur when it runs feature_vectors[tuple(ft.fts(😕).numeric())].append(x), since ft.fts(😕) returns an empty dictionary.

**Comment by zouharvi** [comment]
Hi, sorry for the late response, I didn't see the notification before.

Did you get some further output? I got no errors running the following:
```
python3 ./create_dataset/preprocess.py
python3 ./create_dataset/add_analogies.py
```

Could there be some panphon version mismatch? I have `panphon==0.2.0` and `panphon2==0.3.2`.

**Comment by zouharvi** [comment]
Also, mind that you do not have to recreate the dataset locally. It's much easier to just use the prepared one online, as shown [in the demo](https://github.com/zouharvi/pwesuite/blob/master/demo.ipynb).

```
import datasets
data = datasets.load_dataset("zouharvi/pwesuite-eval", split="train")
```

**Comment by SolveigHelene** [comment]
This occurs when running demo.ipynb, so I am using the online dataset. So I have run all the cells, and then this occurs when running !python3 ./suite_evaluation/eval_all.py --embd embd.npy

This is the whole output I get:
Loading data
Human similarity
Correlations
100%|█████████████████████████████████████████████| 9/9 [01:24<00:00,  9.41s/it]
Retrieval
100%|█████████████████████████████████████████████| 9/9 [01:14<00:00,  8.26s/it]
Sound analogies
Traceback (most recent call last):
  File "/pwesuite/./suite_evaluation/eval_all.py", line 90, in <module>
    score, scores_all = evaluate_all(data_multi, data_embd, args.lang)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pwesuite/./suite_evaluation/eval_all.py", line 59, in evaluate_all
    output = evaluate_analogy(
             ^^^^^^^^^^^^^^^^^
  File "/pwesuite/suite_evaluation/eval_analogy.py", line 69, in evaluate_analogy
    output[lang] = evaluate_analogy_single_lang(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pwesuite/suite_evaluation/eval_analogy.py", line 11, in evaluate_analogy_single_lang
    analogies = get_analogies(data_multi, lang)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pwesuite/create_dataset/add_analogies.py", line 187, in get_analogies
    analogy_model = PhonemeAnalogy(
                    ^^^^^^^^^^^^^^^
  File "/pwesuite/create_dataset/add_analogies.py", line 28, in __init__
    self.single_perturbation_pairs = self.find_single_perturbation_pairs(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pwesuite/create_dataset/add_analogies.py", line 159, in find_single_perturbation_pairs
    feature_vectors[tuple(ft.fts(x).numeric())].append(x)
                          ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'numeric'

**Comment by zouharvi** [comment]
Working on a solution now. :slightly_smiling_face:

**Comment by zouharvi** [comment]
I changed the analogy pipeline (in https://github.com/zouharvi/pwesuite/commit/3eeaeee7433781d641921bf8d9225750508d11b3) so that it does not need to be generated locally (caused many other issues) but is instead pulled from HuggingFace. This should make things more consistent and clean.

Could you update the repo and run the demo again?

**Comment by zouharvi** [comment]
I removed the dependency to create the analogy and cognate data locally. Instead, it's now all in the HF dataset. This should remove bunch of friction points, hopefully. :slightly_smiling_face: 

Could you update the repository and run the demo again?

**Comment by zouharvi** [comment]
Great to hear. Let me know if you discover any other issues. :slightly_smiling_face: 

Btw, for now ([here](https://github.com/zouharvi/pwesuite/blob/7f30c25c6e30959a3e55b911283d1a87959a368a/main/utils.py#L71)) I made it so that the dataset gets downloaded every time (to make sure that you get the latest version when running it). Simply remove the `download_mode="force_redownload"` to just use the already downloaded version.

**Comment by JeffBezos64** [comment]
Hi @zouharvi , the demo runs without issue but for replication purposes it is currently failing. I believe it is the same issue.
